name: Publish Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia con il tuo branch principale se diverso
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install mkdocs-material
        run: pip install mkdocs-material

      - name: Build documentation
        run: mkdocs build --site-dir public

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
